# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_auto_20170227_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Student'),
        ),
    ]
